export const menu = {
  // deals: [
  //   {
  //     category: "Deal",
  //     qty: 0,
  //     totalPrice: 500,
  //     item: "Deal-1",
  //     itemInfo: "",
  //     price: 500,
  //   },
  //   {
  //     category: "Deal",
  //     qty: 0,
  //     totalPrice: 680,
  //     item: "Deal-2",
  //     itemInfo: "",
  //     price: 680,
  //   },
  //   {
  //     category: "Deal",
  //     qty: 0,
  //     totalPrice: 900,
  //     item: "Deal-3",
  //     itemInfo: "",
  //     price: 900,
  //   },
  //   {
  //     category: "Deal",
  //     qty: 0,
  //     totalPrice: 950,
  //     item: "Deal-4",
  //     itemInfo: "",
  //     price: 950,
  //   },
  //   {
  //     category: "Deal",
  //     qty: 0,
  //     totalPrice: 1100,
  //     item: "Deal-5",
  //     itemInfo: "",
  //     price: 1100,
  //   },
  //   {
  //     category: "Deal",
  //     qty: 0,
  //     totalPrice: 1150,
  //     item: "Deal-6",
  //     itemInfo: "",
  //     price: 1150,
  //   },
  //   {
  //     category: "Deal",
  //     qty: 0,
  //     totalPrice: 1200,
  //     item: "Deal-7",
  //     itemInfo: "",
  //     price: 1200,
  //   },
  //   {
  //     category: "Deal",
  //     qty: 0,
  //     totalPrice: 1250,
  //     item: "Deal-8",
  //     itemInfo: "",
  //     price: 1250,
  //   },
  //   {
  //     category: "Deal",
  //     qty: 0,
  //     totalPrice: 1250,
  //     item: "Deal-9",
  //     itemInfo: "",
  //     price: 1250,
  //   },
  //   {
  //     category: "Deal",
  //     qty: 0,
  //     totalPrice: 1350,
  //     item: "Deal-10",
  //     itemInfo: "",
  //     price: 1350,
  //   },
  //   {
  //     category: "Deal",
  //     qty: 0,
  //     totalPrice: 1350,
  //     item: "Deal-11",
  //     itemInfo: "",
  //     price: 1350,
  //   },
  //   {
  //     category: "Deal",
  //     qty: 0,
  //     totalPrice: 1400,
  //     item: "Deal-12",
  //     itemInfo: "",
  //     price: 1400,
  //   },
  //   {
  //     category: "Deal",
  //     qty: 0,
  //     totalPrice: 1870,
  //     item: "Deal-13",
  //     itemInfo: "",
  //     price: 1870,
  //   },
  //   {
  //     category: "Deal",
  //     qty: 0,
  //     totalPrice: 2050,
  //     item: "Deal-14",
  //     itemInfo: "",
  //     price: 2050,
  //   },
  //   {
  //     category: "Deal",
  //     qty: 0,
  //     totalPrice: 2200,
  //     item: "Deal-15",
  //     itemInfo: "",
  //     price: 2200,
  //   },
  //   {
  //     category: "Deal",
  //     qty: 0,
  //     totalPrice: 550,
  //     item: "KMD",
  //     itemInfo: "",
  //     price: 550,
  //   },
  // ],
  //
  deals: {
    pizzaDeals: [
      {
        category: "Pizza Deal",
        qty: 0,
        totalPrice: 500,
        item: "Deal-1",
        itemInfo: "",
        price: 500,
      },
      {
        category: "Pizza Deal",
        qty: 0,
        totalPrice: 700,
        item: "Deal-2",
        itemInfo: "",
        price: 700,
      },
      {
        category: "Pizza Deal",
        qty: 0,
        totalPrice: 900,
        item: "Deal-3",
        itemInfo: "",
        price: 900,
      },
      {
        category: "Pizza Deal",
        qty: 0,
        totalPrice: 1150,
        item: "Deal-4",
        itemInfo: "",
        price: 1150,
      },
      {
        category: "Pizza Deal",
        qty: 0,
        totalPrice: 1550,
        item: "Deal-5",
        itemInfo: "",
        price: 1550,
      },
      {
        category: "Pizza Deal",
        qty: 0,
        totalPrice: 1600,
        item: "Deal-7",
        itemInfo: "",
        price: 1600,
      },
      {
        category: "Pizza Deal",
        qty: 0,
        totalPrice: 1700,
        item: "Deal-8",
        itemInfo: "",
        price: 1700,
      },
      {
        category: "Pizza Deal",
        qty: 0,
        totalPrice: 1800,
        item: "Deal-9",
        itemInfo: "",
        price: 1800,
      },
      {
        category: "Pizza Deal",
        qty: 0,
        totalPrice: 2650,
        item: "Deal-10",
        itemInfo: "",
        price: 2650,
      },
    ],
    fastFoodDeals: [
      {
        category: "Fast Food Deal",
        qty: 0,
        totalPrice: 600,
        item: "Deal-1",
        itemInfo: "",
        price: 600,
      },
      {
        category: "Fast Food Deal",
        qty: 0,
        totalPrice: 700,
        item: "Deal-2",
        itemInfo: "",
        price: 700,
      },
      {
        category: "Fast Food Deal",
        qty: 0,
        totalPrice: 700,
        item: "Deal-3",
        itemInfo: "",
        price: 700,
      },
      {
        category: "Fast Food Deal",
        qty: 0,
        totalPrice: 750,
        item: "Deal-4",
        itemInfo: "",
        price: 750,
      },
      {
        category: "Fast Food Deal",
        qty: 0,
        totalPrice: 950,
        item: "Deal-5",
        itemInfo: "",
        price: 950,
      },
      {
        category: "Fast Food Deal",
        qty: 0,
        totalPrice: 1000,
        item: "Deal-6",
        itemInfo: "",
        price: 1000,
      },
      {
        category: "Fast Food Deal",
        qty: 0,
        totalPrice: 1150,
        item: "Deal-7",
        itemInfo: "",
        price: 1150,
      },
      {
        category: "Fast Food Deal",
        qty: 0,
        totalPrice: 1300,
        item: "Deal-8",
        itemInfo: "",
        price: 1300,
      },
      {
        category: "Fast Food Deal",
        qty: 0,
        totalPrice: 1750,
        item: "Deal-9",
        itemInfo: "",
        price: 1750,
      },
    ],
  },
  // fries: {
  //   small: [
  //     {
  //       category: "Flavour Fries Small",
  //       qty: 0,
  //       totalPrice: 80,
  //       item: "Smoke Tikka",
  //       itemInfo: "",
  //       size: "small",
  //       price: 80,
  //     },
  //     {
  //       category: "Flavour Fries Small",
  //       qty: 0,
  //       totalPrice: 80,
  //       item: "BBQ",
  //       itemInfo: "",
  //       size: "small",
  //       price: 80,
  //     },
  //     {
  //       category: "Flavour Fries Small",
  //       qty: 0,
  //       totalPrice: 80,
  //       item: "Afghani",
  //       itemInfo: "",
  //       size: "small",
  //       price: 80,
  //     },
  //     {
  //       category: "Flavour Fries Small",
  //       qty: 0,
  //       totalPrice: 80,
  //       item: "Jalapeno",
  //       itemInfo: "",
  //       size: "small",
  //       price: 80,
  //     },
  //     {
  //       category: "Flavour Fries Small",
  //       qty: 0,
  //       totalPrice: 80,
  //       item: "Green Chilli",
  //       itemInfo: "",
  //       size: "small",
  //       price: 80,
  //     },
  //     {
  //       category: "Flavour Fries Small",
  //       qty: 0,
  //       totalPrice: 80,
  //       item: "CHEESE CHILLI",
  //       itemInfo: "",
  //       size: "small",
  //       price: 80,
  //     },
  //     {
  //       category: "Flavour Fries Small",
  //       qty: 0,
  //       totalPrice: 80,
  //       item: "BUTTER CHEESE",
  //       itemInfo: "",
  //       size: "small",
  //       price: 80,
  //     },
  //     {
  //       category: "Flavour Fries Small",
  //       qty: 0,
  //       totalPrice: 80,
  //       item: "FAJITA (SPICY)",
  //       itemInfo: "",
  //       size: "small",
  //       price: 80,
  //     },
  //     {
  //       category: "Flavour Fries Small",
  //       qty: 0,
  //       totalPrice: 80,
  //       item: "LEMON",
  //       itemInfo: "",
  //       size: "small",
  //       price: 80,
  //     },
  //     {
  //       category: "Flavour Fries Small",
  //       qty: 0,
  //       totalPrice: 80,
  //       item: "PERI PERI",
  //       itemInfo: "",
  //       size: "small",
  //       price: 80,
  //     },
  //     {
  //       category: "Flavour Fries Small",
  //       qty: 0,
  //       totalPrice: 80,
  //       item: "GARLIC",
  //       itemInfo: "",
  //       size: "small",
  //       price: 80,
  //     },
  //   ],
  //   large: [
  //     {
  //       category: "Flavour Fries Large",
  //       qty: 0,
  //       totalPrice: 120,
  //       item: "Smoke Tikka",
  //       itemInfo: "",
  //       size: "large",
  //       price: 120,
  //     },
  //     {
  //       category: "Flavour Fries Large",
  //       qty: 0,
  //       totalPrice: 120,
  //       item: "BBQ",
  //       itemInfo: "",
  //       size: "large",
  //       price: 120,
  //     },
  //     {
  //       category: "Flavour Fries Large",
  //       qty: 0,
  //       totalPrice: 120,
  //       item: "Afghani",
  //       itemInfo: "",
  //       size: "large",
  //       price: 120,
  //     },
  //     {
  //       category: "Flavour Fries Large",
  //       qty: 0,
  //       totalPrice: 120,
  //       item: "Jalapeno",
  //       itemInfo: "",
  //       size: "large",
  //       price: 120,
  //     },
  //     {
  //       category: "Flavour Fries Large",
  //       qty: 0,
  //       totalPrice: 120,
  //       item: "Green Chilli",
  //       itemInfo: "",
  //       size: "large",
  //       price: 120,
  //     },
  //     {
  //       category: "Flavour Fries Large",
  //       qty: 0,
  //       totalPrice: 120,
  //       item: "CHEESE CHILLI",
  //       itemInfo: "",
  //       size: "large",
  //       price: 120,
  //     },
  //     {
  //       category: "Flavour Fries Large",
  //       qty: 0,
  //       totalPrice: 120,
  //       item: "BUTTER CHEESE",
  //       itemInfo: "",
  //       size: "large",
  //       price: 120,
  //     },
  //     {
  //       category: "Flavour Fries Large",
  //       qty: 0,
  //       totalPrice: 120,
  //       item: "FAJITA (SPICY)",
  //       itemInfo: "",
  //       size: "large",
  //       price: 120,
  //     },
  //     {
  //       category: "Flavour Fries Large",
  //       qty: 0,
  //       totalPrice: 120,
  //       item: "LEMON",
  //       itemInfo: "",
  //       size: "large",
  //       price: 120,
  //     },
  //     {
  //       category: "Flavour Fries Large",
  //       qty: 0,
  //       totalPrice: 120,
  //       item: "PERI PERI",
  //       itemInfo: "",
  //       size: "large",
  //       price: 120,
  //     },
  //     {
  //       category: "Flavour Fries Large",
  //       qty: 0,
  //       totalPrice: 120,
  //       item: "GARLIC",
  //       itemInfo: "",
  //       size: "large",
  //       price: 120,
  //     },
  //   ],
  // },
  // wraps: [
  //   {
  //     category: "wrap",
  //     qty: 0,
  //     totalPrice: 250,
  //     item: "FAJITA WRAP",
  //     itemInfo: "",
  //     price: 250,
  //   },
  //   {
  //     category: "wrap",
  //     qty: 0,
  //     totalPrice: 270,
  //     item: "MALAI WRAP",
  //     itemInfo: "",
  //     price: 270,
  //   },
  //   {
  //     category: "wrap",
  //     qty: 0,
  //     totalPrice: 350,
  //     item: "MEXICAN WRAP",
  //     itemInfo: "",
  //     price: 350,
  //   },
  //   {
  //     category: "wrap",
  //     qty: 0,
  //     totalPrice: 300,
  //     item: "ZINGER WRAP",
  //     itemInfo: "",
  //     price: 300,
  //   },
  // ],
  // pizzaFries: {
  //   small: [
  //     {
  //       category: "Pizza Fries Small",
  //       qty: 0,
  //       totalPrice: 350,
  //       item: "Cheesy chipotale fries",
  //       itemInfo: "",
  //       size: "small",
  //       price: 350,
  //     },
  //     {
  //       category: "Pizza Fries Small",
  //       qty: 0,
  //       totalPrice: 350,
  //       item: "Smoky BBQ Cheese fries",
  //       itemInfo: "",
  //       size: "small",
  //       price: 350,
  //     },
  //     {
  //       category: "Pizza Fries Small",
  //       qty: 0,
  //       totalPrice: 300,
  //       item: "Dragon fries",
  //       itemInfo: "",
  //       size: "small",
  //       price: 300,
  //     },
  //     {
  //       category: "Pizza Fries Small",
  //       qty: 0,
  //       totalPrice: 300,
  //       item: "Loaded fries",
  //       itemInfo: "",
  //       size: "small",
  //       price: 300,
  //     },
  //     {
  //       category: "Pizza Fries Small",
  //       qty: 0,
  //       totalPrice: 420,
  //       item: "BF special cheese fries",
  //       itemInfo: "",
  //       size: "small",
  //       price: 420,
  //     },
  //   ],
  //   large: [
  //     {
  //       category: "Pizza Fries Large",
  //       qty: 0,
  //       totalPrice: 550,
  //       item: "Cheesy chipotale fries",
  //       itemInfo: "",
  //       size: "large",
  //       price: 550,
  //     },
  //     {
  //       category: "Pizza Fries Large",
  //       qty: 0,
  //       totalPrice: 530,
  //       item: "Smoky BBQ Cheese fries",
  //       itemInfo: "",
  //       size: "large",
  //       price: 530,
  //     },
  //     {
  //       category: "Pizza Fries Large",
  //       qty: 0,
  //       totalPrice: 450,
  //       item: "Dragon fries",
  //       itemInfo: "",
  //       size: "large",
  //       price: 450,
  //     },
  //     {
  //       category: "Pizza Fries Large",
  //       qty: 0,
  //       totalPrice: 450,
  //       item: "Loaded fries",
  //       itemInfo: "",
  //       size: "large",
  //       price: 450,
  //     },
  //     {
  //       category: "Pizza Fries Large",
  //       qty: 0,
  //       totalPrice: 590,
  //       item: "BF special cheese fries",
  //       itemInfo: "",
  //       size: "large",
  //       price: 590,
  //     },
  //   ],
  // },
  fries: {
    small: [
      {
        category: "Fries Small",
        qty: 0,
        totalPrice: 100,
        item: "Plain Fries",
        itemInfo: "",
        size: "small",
        price: 100,
      },
      {
        category: "Fries Small",
        qty: 0,
        totalPrice: 100,
        item: "Masala Fries",
        itemInfo: "",
        size: "small",
        price: 100,
      },
      {
        category: "Fries Small",
        qty: 0,
        totalPrice: 200,
        item: "Honey Fries",
        itemInfo: "",
        size: "small",
        price: 200,
      },
      {
        category: "Fries Small",
        qty: 0,
        totalPrice: 200,
        item: "Garlic Fries",
        itemInfo: "",
        size: "small",
        price: 200,
      },
      {
        category: "Fries Small",
        qty: 0,
        totalPrice: 250,
        item: "Chicken Fries",
        itemInfo: "",
        size: "small",
        price: 250,
      },
      {
        category: "Fries Small",
        qty: 0,
        totalPrice: 500,
        item: "Loaded Fries",
        itemInfo: "",
        size: "small",
        price: 500,
      },
      {
        category: "Fries Small",
        qty: 0,
        totalPrice: 500,
        item: "Pizza Fries",
        itemInfo: "",
        size: "small",
        price: 500,
      },
      {
        category: "Fries Small",
        qty: 0,
        totalPrice: 500,
        item: "Chipotle Fries",
        itemInfo: "",
        size: "small",
        price: 500,
      },
      {
        category: "Fries Small",
        qty: 0,
        totalPrice: 500,
        item: "Chicken Crispy Fries",
        itemInfo: "",
        size: "small",
        price: 500,
      },
    ],
    large: [
      {
        category: "Fries Large",
        qty: 0,
        totalPrice: 200,
        item: "Plain Fries",
        itemInfo: "",
        size: "large",
        price: 200,
      },
      {
        category: "Fries Large",
        qty: 0,
        totalPrice: 200,
        item: "Masala Fries",
        itemInfo: "",
        size: "large",
        price: 200,
      },
      {
        category: "Fries Large",
        qty: 0,
        totalPrice: 300,
        item: "Honey Fries",
        itemInfo: "",
        size: "large",
        price: 300,
      },
      {
        category: "Fries Large",
        qty: 0,
        totalPrice: 300,
        item: "Garlic Fries",
        itemInfo: "",
        size: "large",
        price: 300,
      },
      {
        category: "Fries Large",
        qty: 0,
        totalPrice: 450,
        item: "Chicken Fries",
        itemInfo: "",
        size: "large",
        price: 450,
      },
      {
        category: "Fries Large",
        qty: 0,
        totalPrice: 500,
        item: "Loaded Fries",
        itemInfo: "",
        size: "large",
        price: 500,
      },
      {
        category: "Fries Large",
        qty: 0,
        totalPrice: 500,
        item: "Pizza Fries",
        itemInfo: "",
        size: "large",
        price: 500,
      },
      {
        category: "Fries Large",
        qty: 0,
        totalPrice: 500,
        item: "Chipotle Fries",
        itemInfo: "",
        size: "large",
        price: 500,
      },
      {
        category: "Fries Large",
        qty: 0,
        totalPrice: 500,
        item: "Chicken Crispy Fries",
        itemInfo: "",
        size: "large",
        price: 500,
      },
    ],
  },
  chefSpecialists: [
    {
      category: "Chef Specialist",
      qty: 0,
      totalPrice: 550,
      item: "Smoky Wrap",
      price: 550,
    },
    {
      category: "Chef Specialist",
      qty: 0,
      totalPrice: 500,
      item: "Chipotle Fries",
      price: 500,
    },
    {
      category: "Chef Specialist",
      qty: 0,
      totalPrice: 550,
      item: "Loaded Fries",
      price: 550,
    },
    {
      category: "Chef Specialist",
      qty: 0,
      totalPrice: 550,
      item: "Grill Wrap",
      price: 550,
    },
    {
      category: "Chef Specialist",
      qty: 0,
      totalPrice: 600,
      item: "Mighty Burger / Doopler",
      price: 600,
    },
    {
      category: "Chef Specialist",
      qty: 0,
      totalPrice: 700,
      item: "Stuff Burger Chicken",
      price: 700,
    },
    {
      category: "Chef Specialist",
      qty: 0,
      totalPrice: 850,
      item: "Monster Burger Chick",
      price: 850,
    },
  ],
  broasts: [
    {
      category: "Chicken",
      qty: 0,
      totalPrice: 250,
      item: "Wings 3 Pcs",
      price: 250,
    },
    {
      category: "Wrap",
      qty: 0,
      totalPrice: 350,
      item: "Crispy Wrap",
      price: 350,
    },
    {
      category: "Chicken",
      qty: 0,
      totalPrice: 400,
      item: "Chicken Strips",
      price: 400,
    },
    {
      category: "Wrap",
      qty: 0,
      totalPrice: 400,
      item: "Grill Wrap",
      price: 400,
    },
    {
      category: "Chicken",
      qty: 0,
      totalPrice: 450,
      item: "Broast",
      price: 450,
    },
    {
      category: "Chicken",
      qty: 0,
      totalPrice: 450,
      item: "Wings 6 Pcs",
      price: 450,
    },
    {
      category: "Chicken",
      qty: 0,
      totalPrice: 450,
      item: "Drum Stick 4 Pcs",
      price: 450,
    },
    {
      category: "Wrap",
      qty: 0,
      totalPrice: 500,
      item: "Smoky Wrap",
      price: 500,
    },
  ],
  // udpated sandwiches
  sandwiches: [
    {
      category: "Sandwich",
      qty: 0,
      totalPrice: 400,
      item: "Club Sandwich",
      price: 400,
    },
    {
      category: "Sandwich",
      qty: 0,
      totalPrice: 450,
      item: "Crispy Club Sandwich",
      price: 450,
    },
    {
      category: "Sandwich",
      qty: 0,
      totalPrice: 500,
      item: "Maxican Club Sandwich",
      price: 500,
    },
    {
      category: "Sandwich",
      qty: 0,
      totalPrice: 500,
      item: "Lasagne",
      price: 500,
    },
    {
      category: "Pasta",
      qty: 0,
      totalPrice: 500,
      item: "Pasta",
      price: 500,
    },
    {
      category: "Sandwich",
      qty: 0,
      totalPrice: 550,
      item: "Pizza Hub Sandwich",
      price: 550,
    },
    {
      category: "Pasta",
      qty: 0,
      totalPrice: 550,
      item: "Chicken Pasta / Creamy Pasta",
      price: 550,
    },
    {
      category: "Shawarma",
      qty: 0,
      totalPrice: 0, // Price for Shawarma not provided
      item: "Shawarma",
      price: 0, // Price for Shawarma not provided
    },
    {
      category: "Special Shawarma",
      qty: 0,
      totalPrice: 0, // Price for Special Shawarma not provided
      item: "Special Shawarma",
      price: 0, // Price for Special Shawarma not provided
    },
  ],
  // udpated burgers
  burgers: [
    {
      category: "Burger",
      qty: 0,
      totalPrice: 350,
      item: "Chicken Burger",
      price: 350,
    },
    {
      category: "Burger",
      qty: 0,
      totalPrice: 350,
      item: "Crispy Burger",
      price: 350,
    },
    {
      category: "Burger",
      qty: 0,
      totalPrice: 400,
      item: "Beef Burger",
      price: 400,
    },
    {
      category: "Burger",
      qty: 0,
      totalPrice: 400,
      item: "Zinger Burger",
      price: 400,
    },
    {
      category: "Burger",
      qty: 0,
      totalPrice: 400,
      item: "Chicken Grill Burger",
      price: 400,
    },
    {
      category: "Burger",
      qty: 0,
      totalPrice: 400,
      item: "Crispy Spicy Burger",
      price: 400,
    },
    {
      category: "Burger",
      qty: 0,
      totalPrice: 450,
      item: "Zinger Cheese Burger",
      price: 450,
    },
    {
      category: "Burger",
      qty: 0,
      totalPrice: 650,
      item: "Zinger Double Tecker Burger",
      price: 650,
    },
    {
      category: "Burger",
      qty: 0,
      totalPrice: 650,
      item: "Mighty Burger",
      price: 650,
    },
    {
      category: "Burger",
      qty: 0,
      totalPrice: 650,
      item: "Stuff Burger",
      price: 650,
    },
    {
      category: "Burger",
      qty: 0,
      totalPrice: 800,
      item: "Monster Burger",
      price: 800,
    },
  ],
  // pizzas: {
  //   small: [
  //     {
  //       category: "Pizza Small ",
  //       qty: 0,
  //       totalPrice: 200,
  //       item: "TIKKA",
  //       itemInfo: "",
  //       size: "small",
  //       price: 200,
  //     },
  //     {
  //       category: "Pizza Small ",
  //       qty: 0,
  //       totalPrice: 200,
  //       item: "FAJITA",
  //       itemInfo: "",
  //       size: "small",
  //       price: 200,
  //     },
  //     {
  //       category: "Pizza Small ",
  //       qty: 0,
  //       totalPrice: 200,
  //       item: "AFGHANI",
  //       itemInfo: "",
  //       size: "small",
  //       price: 200,
  //     },
  //     {
  //       category: "Pizza Small ",
  //       qty: 0,
  //       totalPrice: 200,
  //       item: "MALAI Boti",
  //       itemInfo: "",
  //       size: "small",
  //       price: 200,
  //     },
  //     {
  //       category: "Pizza Small ",
  //       qty: 0,
  //       totalPrice: 200,
  //       item: "Chees lover",
  //       itemInfo: "",
  //       size: "small",
  //       price: 200,
  //     },
  //     {
  //       category: "Pizza Small ",
  //       qty: 0,
  //       totalPrice: 200,
  //       item: "vegie lover",
  //       itemInfo: "",
  //       size: "small",
  //       price: 200,
  //     },
  //     {
  //       category: "Pizza Small ",
  //       qty: 0,
  //       totalPrice: 250,
  //       item: "Pepproni",
  //       itemInfo: "",
  //       size: "small",
  //       price: 250,
  //     },
  //   ],
  //   medium: [
  //     {
  //       category: "Pizza Medium ",
  //       qty: 0,
  //       totalPrice: 400,
  //       item: "TIKKA",
  //       itemInfo: "",
  //       size: "medium",
  //       price: 400,
  //     },
  //     {
  //       category: "Pizza Medium ",
  //       qty: 0,
  //       totalPrice: 400,
  //       item: "FAJITA",
  //       itemInfo: "",
  //       size: "medium",
  //       price: 400,
  //     },
  //     {
  //       category: "Pizza Medium ",
  //       qty: 0,
  //       totalPrice: 400,
  //       item: "AFGHANI",
  //       itemInfo: "",
  //       size: "medium",
  //       price: 400,
  //     },
  //     {
  //       category: "Pizza Medium ",
  //       qty: 0,
  //       totalPrice: 400,
  //       item: "MALAI Boti",
  //       itemInfo: "",
  //       size: "medium",
  //       price: 400,
  //     },
  //     {
  //       category: "Pizza Medium ",
  //       qty: 0,
  //       totalPrice: 400,
  //       item: "Chees lover",
  //       itemInfo: "",
  //       size: "medium",
  //       price: 400,
  //     },
  //     {
  //       category: "Pizza Medium ",
  //       qty: 0,
  //       totalPrice: 400,
  //       item: "vegie lover",
  //       itemInfo: "",
  //       size: "medium",
  //       price: 400,
  //     },
  //     {
  //       category: "Pizza Medium ",
  //       qty: 0,
  //       totalPrice: 450,
  //       item: "Pepproni",
  //       itemInfo: "",
  //       size: "medium",
  //       price: 450,
  //     },
  //   ],
  //   large: [
  //     {
  //       category: "Pizza Large ",
  //       qty: 0,
  //       totalPrice: 650,
  //       item: "TIKKA",
  //       itemInfo: "",
  //       size: "large",
  //       price: 650,
  //     },
  //     {
  //       category: "Pizza Large ",
  //       qty: 0,
  //       totalPrice: 650,
  //       item: "FAJITA",
  //       itemInfo: "",
  //       size: "large",
  //       price: 650,
  //     },
  //     {
  //       category: "Pizza Large ",
  //       qty: 0,
  //       totalPrice: 650,
  //       item: "AFGHANI",
  //       itemInfo: "",
  //       size: "large",
  //       price: 650,
  //     },
  //     {
  //       category: "Pizza Large ",
  //       qty: 0,
  //       totalPrice: 650,
  //       item: "MALAI Boti",
  //       itemInfo: "",
  //       size: "large",
  //       price: 650,
  //     },
  //     {
  //       category: "Pizza Large ",
  //       qty: 0,
  //       totalPrice: 650,
  //       item: "Chees lover",
  //       itemInfo: "",
  //       size: "large",
  //       price: 650,
  //     },
  //     {
  //       category: "Pizza Large ",
  //       qty: 0,
  //       totalPrice: 650,
  //       item: "vegie lover",
  //       itemInfo: "",
  //       size: "large",
  //       price: 650,
  //     },
  //     {
  //       category: "Pizza Large ",
  //       qty: 0,
  //       totalPrice: 700,
  //       item: "Pepproni",
  //       itemInfo: "",
  //       size: "large",
  //       price: 700,
  //     },
  //   ],
  // },

  pizzas: {
    small: [
      {
        category: "Pizza Small ",
        qty: 0,
        totalPrice: 250,
        item: "Tikka",
        itemInfo: "",
        size: "small",
        price: 250,
      },
      {
        category: "Pizza Small ",
        qty: 0,
        totalPrice: 250,
        item: "Hot & Spicy",
        itemInfo: "",
        size: "small",
        price: 250,
      },
      {
        category: "Pizza Small ",
        qty: 0,
        totalPrice: 250,
        item: "Afghani Tikka",
        itemInfo: "",
        size: "small",
        price: 250,
      },
      {
        category: "Pizza Small ",
        qty: 0,
        totalPrice: 250,
        item: "Chicken Super",
        itemInfo: "",
        size: "small",
        price: 250,
      },
      {
        category: "Pizza Small ",
        qty: 0,
        totalPrice: 250,
        item: "Creamy Tikka",
        itemInfo: "",
        size: "small",
        price: 250,
      },
      {
        category: "Pizza Small ",
        qty: 0,
        totalPrice: 250,
        item: "Creamy Pearl",
        itemInfo: "",
        size: "small",
        price: 250,
      },
      {
        category: "Pizza Small ",
        qty: 0,
        totalPrice: 250,
        item: "Malai Boti",
        itemInfo: "",
        size: "small",
        price: 250,
      },
      {
        category: "Pizza Small ",
        qty: 0,
        totalPrice: 250,
        item: "Fajita Sensation",
        itemInfo: "",
        size: "small",
        price: 250,
      },
      {
        category: "Pizza Small ",
        qty: 0,
        totalPrice: 250,
        item: "Chicken Fajita",
        itemInfo: "",
        size: "small",
        price: 250,
      },
      {
        category: "Pizza Small ",
        qty: 0,
        totalPrice: 250,
        item: "Italian Light & Spicy",
        itemInfo: "",
        size: "small",
        price: 250,
      },
    ],
    medium: [
      {
        category: "Pizza Medium ",
        qty: 0,
        totalPrice: 500,
        item: "Tikka",
        itemInfo: "",
        size: "medium",
        price: 500,
      },
      {
        category: "Pizza Medium ",
        qty: 0,
        totalPrice: 500,
        item: "Hot & Spicy",
        itemInfo: "",
        size: "medium",
        price: 500,
      },
      {
        category: "Pizza Medium ",
        qty: 0,
        totalPrice: 500,
        item: "Afghani Tikka",
        itemInfo: "",
        size: "medium",
        price: 500,
      },
      {
        category: "Pizza Medium ",
        qty: 0,
        totalPrice: 500,
        item: "Chicken Super",
        itemInfo: "",
        size: "medium",
        price: 500,
      },
      {
        category: "Pizza Medium ",
        qty: 0,
        totalPrice: 500,
        item: "Creamy Tikka",
        itemInfo: "",
        size: "medium",
        price: 500,
      },
      {
        category: "Pizza Medium ",
        qty: 0,
        totalPrice: 500,
        item: "Creamy Pearl",
        itemInfo: "",
        size: "medium",
        price: 500,
      },
      {
        category: "Pizza Medium ",
        qty: 0,
        totalPrice: 500,
        item: "Malai Boti",
        itemInfo: "",
        size: "medium",
        price: 500,
      },
      {
        category: "Pizza Medium ",
        qty: 0,
        totalPrice: 500,
        item: "Fajita Sensation",
        itemInfo: "",
        size: "medium",
        price: 500,
      },
      {
        category: "Pizza Medium ",
        qty: 0,
        totalPrice: 500,
        item: "Chicken Fajita",
        itemInfo: "",
        size: "medium",
        price: 500,
      },
      {
        category: "Pizza Medium ",
        qty: 0,
        totalPrice: 500,
        item: "Italian Light & Spicy",
        itemInfo: "",
        size: "medium",
        price: 500,
      },
    ],
    large: [
      {
        category: "Pizza Large ",
        qty: 0,
        totalPrice: 700,
        item: "Tikka",
        itemInfo: "",
        size: "large",
        price: 700,
      },
      {
        category: "Pizza Large ",
        qty: 0,
        totalPrice: 700,
        item: "Hot & Spicy",
        itemInfo: "",
        size: "large",
        price: 700,
      },
      {
        category: "Pizza Large ",
        qty: 0,
        totalPrice: 700,
        item: "Afghani Tikka",
        itemInfo: "",
        size: "large",
        price: 700,
      },
      {
        category: "Pizza Large ",
        qty: 0,
        totalPrice: 700,
        item: "Chicken Super",
        itemInfo: "",
        size: "large",
        price: 700,
      },
      {
        category: "Pizza Large ",
        qty: 0,
        totalPrice: 700,
        item: "Creamy Tikka",
        itemInfo: "",
        size: "large",
        price: 700,
      },
      {
        category: "Pizza Large ",
        qty: 0,
        totalPrice: 700,
        item: "Creamy Pearl",
        itemInfo: "",
        size: "large",
        price: 700,
      },
      {
        category: "Pizza Large ",
        qty: 0,
        totalPrice: 700,
        item: "Malai Boti",
        itemInfo: "",
        size: "large",
        price: 700,
      },
      {
        category: "Pizza Large ",
        qty: 0,
        totalPrice: 700,
        item: "Fajita Sensation",
        itemInfo: "",
        size: "large",
        price: 700,
      },
      {
        category: "Pizza Large ",
        qty: 0,
        totalPrice: 700,
        item: "Chicken Fajita",
        itemInfo: "",
        size: "large",
        price: 700,
      },
      {
        category: "Pizza Large ",
        qty: 0,
        totalPrice: 700,
        item: "Italian Light & Spicy",
        itemInfo: "",
        size: "large",
        price: 700,
      },
    ],
  },
  lavaPizzas: [
    {
      category: "Lava Pizza ",
      qty: 0,
      totalPrice: 700,
      item: "Lava Pizza",
      itemInfo: "",
      size: "large",
      price: 700,
    },
  ],
  softDrinks: [
    {
      category: "Soft Drink",
      qty: 0,
      totalPrice: 50, // Price not provided for Water
      item: "Water Small",
      price: 50, // Price not provided for Water
    },
    {
      category: "Soft Drink",
      qty: 0,
      totalPrice: 100, // Price not provided for Water
      item: "Water Large 1 Ltr",
      price: 100, // Price not provided for Water
    },
    {
      category: "Soft Drink",
      qty: 0,
      totalPrice: 180, // Price not provided for Water
      item: "1 Ltr Drink",
      price: 180, // Price not provided for Water
    },
    {
      category: "Soft Drink",
      qty: 0,
      totalPrice: 130, // Price not provided for Water
      item: "Soft Drink 500ml",
      price: 130, // Price not provided for Soft Drink 500ml
    },
    {
      category: "Soft Drink",
      qty: 0,
      totalPrice: 100, // Price not provided for Soft Drink 345ml
      item: "Soft Drink 345ml",
      price: 100, // Price not provided for Soft Drink 345ml
    },
    {
      category: "Soft Drink",
      qty: 0,
      totalPrice: 150, // Price not provided for Soft Drink 500ml
      item: "Sting 500ml",
      price: 150, // Price not provided for Sting 500ml
    },
    {
      category: "Soft Drink",
      qty: 0,
      totalPrice: 120, // Price not provided for Soft Drink Sting
      item: "Sting 345ml",
      price: 120, // Price not provided for Sting
    },
  ],
  // dips: [
  //   {
  //     category: "Dip",
  //     qty: 0,
  //     totalPrice: 50,
  //     item: "GARLIC MAYO",
  //     itemInfo: "",
  //     price: 50,
  //   },
  //   {
  //     category: "Dip",
  //     qty: 0,
  //     totalPrice: 50,
  //     item: "CHIPOTALE",
  //     itemInfo: "",
  //     price: 50,
  //   },
  //   {
  //     category: "Dip",
  //     qty: 0,
  //     totalPrice: 50,
  //     item: "HONEY MUSTARD",
  //     itemInfo: "",
  //     price: 50,
  //   },
  //   {
  //     category: "Dip",
  //     qty: 0,
  //     totalPrice: 50,
  //     item: "BBQ",
  //     itemInfo: "",
  //     price: 50,
  //   },
  //   {
  //     category: "Dip",
  //     qty: 0,
  //     totalPrice: 50,
  //     item: "JALAPENO",
  //     itemInfo: "",
  //     price: 50,
  //   },
  // ],
  dips: [
    {
      category: "Extra",
      qty: 0,
      totalPrice: 50,
      item: "Cheese",
      itemInfo: "",
      price: 50,
    },
    {
      category: "Extra",
      qty: 0,
      totalPrice: 50,
      item: "Coleslaw",
      itemInfo: "",
      price: 50,
    },
    {
      category: "Extra",
      qty: 0,
      totalPrice: 50,
      item: "Raita",
      itemInfo: "",
      price: 50,
    },
    {
      category: "Extra",
      qty: 0,
      totalPrice: 50,
      item: "Dip Sauce",
      itemInfo: "",
      price: 50,
    },
    {
      category: "Extra",
      qty: 0,
      totalPrice: 100,
      item: "Extra Meat Topping",
      itemInfo: "",
      price: 100,
    },
    {
      category: "Extra",
      qty: 0,
      totalPrice: 100,
      item: "Extra Cheese Topping",
      itemInfo: "",
      price: 100,
    },
  ],
};
